---
- name: Download flannel manifest
  become: false
  get_url:
    url: https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
    dest: $HOME/flannel.yml

- name: Set interfaces flannel should look at
  become: false
  lineinfile:
    path: $HOME/flannel.yml
    insertafter: '        - --kube-subnet-mgr'
    line: '        - --iface-regex={{ flannel_iface_regex }}'

- name: Deploy flannel to the cluster
  become: false
  kubernetes.core.k8s:
    src: $HOME/flannel.yml
    state: present

- name: Wait for flannel pods to be ready
  become: false
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Pod
    namespace: kube-flannel
    label_selectors:
      - app=flannel
    wait: true
    wait_condition:
      type: Ready
      status: "True"
    wait_timeout: 300
