---
- hosts: all
  become: true
  tags:
  - setup
  roles:
  - common
  - crio
  - k8s/common

- hosts: masters
  become: true
  tags:
  - init
  roles:
  - k8s/init
  - flannel

- hosts: workers
  become: true
  tags:
  - join
  roles:
  - k8s/join

- hosts: masters
  become: false
  tags:
  - mesh
  roles:
  - istio

- hosts: masters
  become: false
  tags:
  - telemetry
  roles:
  - istio/addons

- hosts: masters
  become: false
  tags:
  - chaos
  roles:
  - chaos-mesh
