---
- name: Check if system is supported
  assert:
    that:
      - ansible_distribution == "Ubuntu"
      - ansible_distribution_version is version('20.04', '>=' )
    fail_msg: "This playbook requires Ubuntu 20.04 or newer"

- name: Disable swap
  shell: swapoff -a

- name: Add k8s configiguration file to /etc/modules-load.d/
  copy:
    src: modules-load.conf
    dest: /etc/modules-load.d/k8s.conf
    owner: root
    group: root

- name: Ensure br_netfilter module is loaded
  shell: modprobe br_netfilter

- name: Ensure iptables correctly see bridged traffic
  copy:
    src: iptables.conf
    dest: /etc/sysctl.d/k8s.conf
    owner: root
    group: root

- name: Force sysctl to load settings from all system conf files
  shell: sysctl --system

- name: Create keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download the Kubernetes signing key
  get_url:
    url: https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_major_version }}/deb/Release.key
    dest: /tmp/kubernetes-apt-key.gpg
    mode: '0644'

- name: Add Kubernetes GPG key
  shell: |
    gpg --dearmor < /tmp/kubernetes-apt-key.gpg > /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add the Kubernetes apt repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_major_version }}/deb/ /"
    filename: kubernetes
    state: present

- name: Install kubelet, kubeadm, and kubectl
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - kubelet={{ kubernetes_version }}
    - kubeadm={{ kubernetes_version }}
    - kubectl={{ kubernetes_version }}

- name: Hold kubelet, kubeadm, and kubectl packages
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl

- name: Clean up temporary key file
  file:
    path: /tmp/kubernetes-apt-key.gpg
    state: absent
